-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 15:01:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `table_file_remover`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `table_file_remover` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(255) NOT NULL,
  `file_location` VARCHAR(255) NOT NULL,
  `file_added_on` DATETIME NOT NULL,
  `file_last_processed_on` DATETIME NULL,
  `file_status` VARCHAR(45) NOT NULL DEFAULT 'IN_PROCESS',
  `file_origin` VARCHAR(45) NOT NULL DEFAULT 'cbcXX',
  `file_type` VARCHAR(45) NOT NULL,
  `file_action` VARCHAR(45) NULL,
  `file_submitted_by` VARCHAR(45) NULL,
  `updated_by` VARCHAR(255) NULL DEFAULT 'SELECT USER()',
  PRIMARY KEY (`file_id`),
  UNIQUE INDEX `file_id_UNIQUE` (`file_id` ASC) VISIBLE,
  UNIQUE INDEX `table_file_removercol_UNIQUE` (`file_name` ASC) VISIBLE,
  UNIQUE INDEX `file_location_UNIQUE` (`file_location` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `table_file_validator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `table_file_validator` (
  `validation_id` INT NOT NULL,
  `file_id` INT NULL,
  `validation_result_location` VARCHAR(255) NOT NULL,
  `validation_notification_arn` VARCHAR(255) NULL,
  `validation_date` DATETIME NULL,
  `validation_status` VARCHAR(45) NULL DEFAULT 'NOT_PROCESSED',
  `validation_type` VARCHAR(45) NULL DEFAULT 'AUTOMATIC',
  `updated_by` VARCHAR(255) NULL DEFAULT 'SELECT USER()',
  PRIMARY KEY (`validation_id`),
  UNIQUE INDEX `validation_id_UNIQUE` (`validation_id` ASC) VISIBLE,
  INDEX `fk_file_id_idx` (`file_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_id`
    FOREIGN KEY (`file_id`)
    REFERENCES `table_file_remover` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `table_file_dbloader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `table_file_dbloader` (
  `load_id` INT NOT NULL,
  `load_validation_id` INT NOT NULL,
  `load_result_location` VARCHAR(255) NOT NULL,
  `load_date` DATETIME NOT NULL,
  `load_status` VARCHAR(45) NOT NULL,
  `load_notification_arn` VARCHAR(255) NULL,
  `load_type` VARCHAR(45) NULL DEFAULT 'AUTOMATIC',
  `load_reason` TEXT NULL COMMENT 'If Data is reloaded, store the reason for the reload',
  `updated_by` VARCHAR(255) NULL DEFAULT 'SELECT USER()',
  PRIMARY KEY (`load_id`),
  INDEX `fk_validation_id_idx` (`load_validation_id` ASC) VISIBLE,
  CONSTRAINT `fk_validation_id`
    FOREIGN KEY (`load_validation_id`)
    REFERENCES `table_file_validator` (`validation_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;