-- MySQL Script generated by MySQL Workbench
-- Tue Dec  8 16:32:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `table_file_remover`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `table_file_validator` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `orig_file_id` INT NULL,
  `validation_file_location` VARCHAR(255) NULL,
  `validation_result_location` VARCHAR(255) NOT NULL,
  `validation_notification_arn` VARCHAR(255) NULL,
  `validation_date` DATETIME NULL,
  `validation_status` VARCHAR(45) NULL DEFAULT 'NOT_PROCESSED',
  `validation_type` VARCHAR(45) NULL DEFAULT 'AUTOMATIC',
  PRIMARY KEY (`file_id`),
  INDEX `fk_file_id_idx` (`orig_file_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_id`
    FOREIGN KEY (`orig_file_id`)
    REFERENCES `table_file_remover` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1000;

-- -----------------------------------------------------
-- Table `table_file_validator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `table_file_validator` (
  `validation_id` INT NOT NULL,
  `orig_file_id` INT NULL,
  `file_id` INT NULL AUTO_INCREMENT,
  `validation_result_location` VARCHAR(255) NOT NULL,
  `validation_notification_arn` VARCHAR(255) NULL,
  `validation_date` DATETIME NULL,
  `validation_status` VARCHAR(45) NULL DEFAULT 'NOT_PROCESSED',
  `validation_type` VARCHAR(45) NULL DEFAULT 'AUTOMATIC',
  `updated_by` VARCHAR(255) NULL DEFAULT 'SELECT USER()',
  `table_file_validatorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`validation_id`),
  UNIQUE INDEX `validation_id_UNIQUE` (`validation_id` ASC) VISIBLE,
  INDEX `fk_file_id_idx` (`orig_file_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_id`
    FOREIGN KEY (`orig_file_id`)
    REFERENCES `table_file_remover` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
